var Ewos = Ewos || {};
(function() {
	try {
		var allData = [
			// company: [
				{id: 'c_0', text: '四川三思德科技有限公司', name: '四川三思德科技有限公司', iconSkin: 'department', type: 'department'
, enable: 1, type: 0, open: 1},

			// ],
			// department: [
				{id: 'd_1', text: '高新区', name: '高新区', iconSkin: 'department', type: 'department', pId: 'd_0', type
: 3, enable: 1, open: 1},
{id: 'd_2', text: '产品部', name: '产品部', iconSkin: 'department', type: 'department', pId: 'd_1', type: 3
, enable: 1, open: 1},
{id: 'd_3', text: '游戏部', name: '游戏部', iconSkin: 'department', type: 'department', pId: 'd_1', type: 3
, enable: 1, open: 1},
{id: 'd_4', text: '市场部', name: '市场部', iconSkin: 'department', type: 'department', pId: 'd_1', type: 3
, enable: 1, open: 1},
{id: 'd_5', text: '编辑部', name: '编辑部', iconSkin: 'department', type: 'department', pId: 'd_1', type: 3
, enable: 1, open: 1},
{id: 'd_6', text: '金牛区分公司', name: '金牛区分公司', iconSkin: 'department', type: 'department', pId: 'd_0', type
: 3, enable: 1, open: 1},
{id: 'd_7', text: '推广部', name: '推广部', iconSkin: 'department', type: 'department', pId: 'd_6', type: 3
, enable: 1, open: 1},
{id: 'd_9', text: '人事部', name: '人事部', iconSkin: 'department', type: 'department', pId: 'd_1', type: 3
, enable: 1, open: 1},
{id: 'd_10', text: '综合部', name: '综合部', iconSkin: 'department', type: 'department', pId: 'd_1', type:
 3, enable: 1, open: 1},
{id: 'd_11', text: '财务部', name: '财务部', iconSkin: 'department', type: 'department', pId: 'd_1', type:
 3, enable: 1, open: 1},

			// ],
			// position: [
				{id: 'p_1', text: '总经理', name: '总经理', iconSkin: 'position', type: 'position', pId:'f_1', enable:
 1, open: 0},
{id: 'p_2', text: '部门经理', name: '部门经理', iconSkin: 'position', type: 'position', pId:'f_1', enable: 1
, open: 0},
{id: 'p_3', text: '职员', name: '职员', iconSkin: 'position', type: 'position', pId:'f_1', enable: 1, open
: 0},
{id: 'p_5', text: '运营总监', name: '运营总监', iconSkin: 'position', type: 'position', pId:'f_1', enable: 1
, open: 0},

			// ],
			// user: [
				{id: 'u_1', 
                text: '管理员', 
                name: '管理员', 
                phone: '13148484587', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=1&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=1&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=1&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=1&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=1',
                department:'',
                position: 'p_1'},
{id: 'u_2', 
                text: '李小波', 
                name: '李小波', 
                phone: '13408078484', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=2&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=2&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=2&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=2&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=2',
                department:'',
                position: 'p_5'},
{id: 'u_3', 
                text: '刘某某', 
                name: '刘某某', 
                phone: '13548130064', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=3&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=3&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=3&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=3&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=3',
                department:'d_4',
                position: ''},
{id: 'u_4', 
                text: '某某', 
                name: '某某', 
                phone: '15756238444', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=4&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=4&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=4&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=4&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=4',
                department:'',
                position: 'p_1'},
{id: 'u_19', 
                text: '产品部测试号', 
                name: '产品部测试号', 
                phone: '13880446756', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=19&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=19&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=19&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=19&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=19',
                department:'d_4,d_2',
                position: 'p_3'},
{id: 'u_5', 
                text: '宛某某', 
                name: '宛某某', 
                phone: '13980743990', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=5&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=5&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=5&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=5&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=5',
                department:'d_10',
                position: 'p_2'},
{id: 'u_6', 
                text: '杨青', 
                name: '杨青', 
                phone: '15208323717', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=6&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=6&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=6&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=6&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=6',
                department:'d_9',
                position: 'p_2,p_3'},
{id: 'u_7', 
                text: '彭某某', 
                name: '彭某某', 
                phone: '18281695898', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=7&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=7&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=7&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=7&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=7',
                department:'d_2',
                position: 'p_3'},
{id: 'u_8', 
                text: '安某某', 
                name: '安某某', 
                phone: '13281237568', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=8&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=8&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=8&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=8&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=8',
                department:'d_2',
                position: 'p_3'},
{id: 'u_9', 
                text: '税某某', 
                name: '税某某', 
                phone: '15314605121', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=9&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=9&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=9&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=9&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=9',
                department:'d_2',
                position: 'p_3'},
{id: 'u_11', 
                text: '郑亚利', 
                name: '郑亚利', 
                phone: '18200132067', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=11&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=11&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=11&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=11&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=11',
                department:'d_2',
                position: 'p_3'},
{id: 'u_12', 
                text: '谢大神', 
                name: '谢大神', 
                phone: '18244295938', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=12&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=12&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=12&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=12&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=12',
                department:'d_2',
                position: 'p_3'},
{id: 'u_14', 
                text: '魏长江', 
                name: '魏长江', 
                phone: '18780024520', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=14&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=14&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=14&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=14&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=14',
                department:'d_2',
                position: 'p_3'},
{id: 'u_17', 
                text: '韩大姐', 
                name: '韩大姐', 
                phone: '18602857571', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=17&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=17&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=17&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=17&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=17',
                department:'d_5',
                position: 'p_2'},
{id: 'u_22', 
                text: '刘老倌', 
                name: '刘老倌', 
                phone: '18782561386', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=22&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=22&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=22&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=22&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=22',
                department:'d_5',
                position: 'p_3'},
{id: 'u_24', 
                text: '黄哥', 
                name: '黄哥', 
                phone: '13980908782', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=24&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=24&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=24&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=24&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=24',
                department:'d_4',
                position: 'p_2'},
{id: 'u_25', 
                text: '朱某某', 
                name: '朱某某', 
                phone: '18780107812', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=25&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=25&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=25&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=25&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=25',
                department:'d_4',
                position: 'p_3'},
{id: 'u_26', 
                text: '何某某', 
                name: '何某某', 
                phone: '18280151193', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=26&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=26&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=26&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=26&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=26',
                department:'d_4',
                position: 'p_3'},
{id: 'u_27', 
                text: '何某某', 
                name: '何某某', 
                phone: '18215629553', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=27&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=27&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=27&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=27&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=27',
                department:'d_4',
                position: 'p_3'},
{id: 'u_28', 
                text: '王某某', 
                name: '王某某', 
                phone: '13678028369', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=28&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=28&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=28&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=28&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=28',
                department:'d_3',
                position: 'p_2'},
{id: 'u_29', 
                text: '马某某', 
                name: '马某某', 
                phone: '13708067774', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=29&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=29&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=29&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=29&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=29',
                department:'d_3',
                position: 'p_3'},
{id: 'u_31', 
                text: '胡某某', 
                name: '胡某某', 
                phone: '18228003871', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=31&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=31&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=31&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=31&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=31',
                department:'d_3',
                position: 'p_3'},
{id: 'u_34', 
                text: '黄某某', 
                name: '黄某某', 
                phone: '18384130247', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=34&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=34&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=34&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=34&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=34',
                department:'d_3',
                position: 'p_3'},
{id: 'u_36', 
                text: '李某某', 
                name: '李某某', 
                phone: '18280161020', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=36&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=36&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=36&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=36&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=36',
                department:'d_3',
                position: 'p_3'},
{id: 'u_37', 
                text: '张浩', 
                name: '张浩', 
                phone: '18380393986', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=37&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=37&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=37&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=37&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=37',
                department:'d_3',
                position: 'p_3'},
{id: 'u_38', 
                text: '梁妹纸', 
                name: '梁妹纸', 
                phone: '18782065836', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=38&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=38&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=38&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=38&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=38',
                department:'d_3',
                position: 'p_3'},
{id: 'u_39', 
                text: '宿青妹纸', 
                name: '宿青妹纸', 
                phone: '18224486601', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=39&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=39&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=39&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=39&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=39',
                department:'d_10',
                position: 'p_3'},
{id: 'u_40', 
                text: '赵姐姐', 
                name: '赵姐姐', 
                phone: '18681352603', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=40&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=40&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=40&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=40&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=40',
                department:'d_11',
                position: 'p_2'},
{id: 'u_41', 
                text: '涂妹纸', 
                name: '涂妹纸', 
                phone: '18328739870', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=41&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=41&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=41&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=41&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=41',
                department:'d_11',
                position: 'p_3'},
{id: 'u_42', 
                text: '王妹纸', 
                name: '王妹纸', 
                phone: '13686478407', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=42&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=42&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=42&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=42&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=42',
                department:'d_11',
                position: 'p_3'},
{id: 'u_43', 
                text: '米杰', 
                name: '米杰', 
                phone: '15756205444', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=43&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=43&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=43&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=43&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=43',
                department:'d_7',
                position: 'p_2'},
{id: 'u_44', 
                text: '唐大神', 
                name: '唐大神', 
                phone: '13730602444', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=44&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=44&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=44&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=44&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=44',
                department:'d_7',
                position: 'p_3'},
{id: 'u_45', 
                text: '李东', 
                name: '李东', 
                phone: '15002875893', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=45&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=45&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=45&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=45&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=45',
                department:'d_7',
                position: 'p_3'},
{id: 'u_46', 
                text: '吕小布', 
                name: '吕小布', 
                phone: '18200453913', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=46&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=46&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=46&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=46&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=46',
                department:'d_7',
                position: 'p_3'},
{id: 'u_47', 
                text: '黄时勇', 
                name: '黄时勇', 
                phone: '18782912440', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=47&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=47&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=47&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=47&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=47',
                department:'d_7',
                position: 'p_3'},
{id: 'u_48', 
                text: '肖忠青', 
                name: '肖忠青', 
                phone: '18096367026', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=48&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=48&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=48&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=48&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=48',
                department:'d_7',
                position: 'p_3'},
{id: 'u_49', 
                text: '张皓然', 
                name: '张皓然', 
                phone: '18615757250', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=49&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=49&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=49&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=49&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=49',
                department:'d_7',
                position: 'p_3'},
{id: 'u_51', 
                text: '刘利', 
                name: '刘利', 
                phone: '15908173832', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=51&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=51&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=51&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=51&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=51',
                department:'d_7',
                position: 'p_3'},
{id: 'u_52', 
                text: '彭树川', 
                name: '彭树川', 
                phone: '13540603286', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=52&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=52&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=52&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=52&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=52',
                department:'d_7',
                position: 'p_3'},
{id: 'u_53', 
                text: '泽朗初', 
                name: '泽朗初', 
                phone: '18990409549', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=53&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=53&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=53&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=53&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=53',
                department:'d_7',
                position: 'p_3'},
{id: 'u_54', 
                text: '何琴', 
                name: '何琴', 
                phone: '18382446091', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=54&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=54&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=54&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=54&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=54',
                department:'d_7',
                position: 'p_3'},
{id: 'u_55', 
                text: '余薛', 
                name: '余薛', 
                phone: '15828286426', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=55&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=55&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=55&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=55&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=55',
                department:'d_7',
                position: 'p_3'},
{id: 'u_56', 
                text: '王超', 
                name: '王超', 
                phone: '13551363626', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=56&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=56&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=56&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=56&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=56',
                department:'d_7',
                position: 'p_3'},
{id: 'u_57', 
                text: '吴明洋', 
                name: '吴明洋', 
                phone: '13679075002', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=57&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=57&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=57&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=57&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=57',
                department:'d_7',
                position: 'p_3'},
{id: 'u_59', 
                text: '徐丽华', 
                name: '徐丽华', 
                phone: '15198076040', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=59&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=59&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=59&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=59&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=59',
                department:'d_7',
                position: 'p_3'},
{id: 'u_58', 
                text: '李辉', 
                name: '李辉', 
                phone: '13666264391', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=58&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=58&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=58&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=58&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=58',
                department:'d_7',
                position: 'p_3'},
{id: 'u_60', 
                text: '刘华川', 
                name: '刘华川', 
                phone: '18280422972', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=60&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=60&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=60&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=60&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=60',
                department:'d_2',
                position: 'p_3'},
{id: 'u_61', 
                text: '蒋自明', 
                name: '蒋自明', 
                phone: '13228100791', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=61&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=61&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=61&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=61&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=61',
                department:'d_2',
                position: 'p_3'},
{id: 'u_62', 
                text: '杨路', 
                name: '杨路', 
                phone: '18224086916', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=62&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=62&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=62&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=62&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=62',
                department:'d_2',
                position: 'p_3'},
{id: 'u_63', 
                text: '蹇志泽', 
                name: '蹇志泽', 
                phone: '18583648251', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=63&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=63&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=63&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=63&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=63',
                department:'d_5',
                position: 'p_3'},
{id: 'u_65', 
                text: '李有圣', 
                name: '李有圣', 
                phone: '18369959937', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=65&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=65&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=65&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=65&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=65',
                department:'d_4',
                position: 'p_3'},
{id: 'u_67', 
                text: '李国文', 
                name: '李国文', 
                phone: '13990604247', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=67&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=67&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=67&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=67&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=67',
                department:'d_4',
                position: 'p_3'},
{id: 'u_69', 
                text: '崔姐姐', 
                name: '崔姐姐', 
                phone: '13882244498', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=69&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=69&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=69&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=69&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=69',
                department:'d_3',
                position: 'p_3'},
{id: 'u_70', 
                text: '王沾元', 
                name: '王沾元', 
                phone: '18613207592', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=70&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=70&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=70&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=70&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=70',
                department:'d_4',
                position: 'p_3'},
{id: 'u_71', 
                text: '邹传海', 
                name: '邹传海', 
                phone: '18983519396', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=71&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=71&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=71&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=71&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=71',
                department:'d_2',
                position: 'p_3'},
{id: 'u_72', 
                text: '徐玉莲', 
                name: '徐玉莲', 
                phone: '15114091914', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=72&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=72&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=72&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=72&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=72',
                department:'d_5',
                position: 'p_3'},
{id: 'u_73', 
                text: '冯鹏', 
                name: '冯鹏', 
                phone: '18782288967', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=73&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=73&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=73&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=73&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=73',
                department:'d_2',
                position: 'p_3'},
{id: 'u_74', 
                text: '李婧琳', 
                name: '李婧琳', 
                phone: '18328361364', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=74&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=74&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=74&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=74&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=74',
                department:'d_2',
                position: 'p_3'},
{id: 'u_75', 
                text: '刘妹纸', 
                name: '刘妹纸', 
                phone: '18328453084', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=75&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=75&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=75&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=75&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=75',
                department:'d_4',
                position: 'p_3'},
{id: 'u_77', 
                text: '赖兄弟', 
                name: '赖兄弟', 
                phone: '18381692547', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=77&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=77&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=77&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=77&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=77',
                department:'d_4',
                position: 'p_3'},
{id: 'u_79', 
                text: '杜帅', 
                name: '杜帅', 
                phone: '18200111698', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=79&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=79&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=79&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=79&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=79',
                department:'d_4',
                position: 'p_3'},
{id: 'u_81', 
                text: '刘庆', 
                name: '刘庆', 
                phone: '13980046254', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=81&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=81&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=81&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=81&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=81',
                department:'d_4',
                position: 'p_3'},
{id: 'u_82', 
                text: '袁美女', 
                name: '袁美女', 
                phone: '18583256623', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=82&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=82&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=82&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=82&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=82',
                department:'d_4',
                position: 'p_3'},
{id: 'u_84', 
                text: '徐刚', 
                name: '徐刚', 
                phone: '13699008153', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=84&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=84&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=84&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=84&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=84',
                department:'d_4',
                position: 'p_3'},
{id: 'u_85', 
                text: '测试号', 
                name: '测试号', 
                phone: '13649040608', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=85&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=85&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=85&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=85&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=85',
                department:'d_10',
                position: 'p_2'},
{id: 'u_86', 
                text: '冉妹纸', 
                name: '冉妹纸', 
                phone: '18482241220', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=86&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=86&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=86&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=86&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=86',
                department:'d_4',
                position: 'p_3'},
{id: 'u_88', 
                text: '杨盼盼', 
                name: '杨盼盼', 
                phone: '13693438497', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=88&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=88&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=88&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=88&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=88',
                department:'d_4',
                position: 'p_3'},
{id: 'u_94', 
                text: '杜某某', 
                name: '杜某某', 
                phone: '18141388962', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=94&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=94&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=94&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=94&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=94',
                department:'d_4',
                position: 'p_3'},
{id: 'u_89', 
                text: '潘美女', 
                name: '潘美女', 
                phone: '18482135625', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=89&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=89&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=89&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=89&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=89',
                department:'d_4',
                position: 'p_3'},
{id: 'u_90', 
                text: '段少爷', 
                name: '段少爷', 
                phone: '15882069522', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=90&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=90&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=90&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=90&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=90',
                department:'d_4',
                position: 'p_3'},
{id: 'u_92', 
                text: '王黎明', 
                name: '王黎明', 
                phone: '18981858909', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=92&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=92&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=92&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=92&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=92',
                department:'d_3',
                position: 'p_3'},
{id: 'u_93', 
                text: '唐妹纸', 
                name: '唐妹纸', 
                phone: '18428314577', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=93&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=93&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=93&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=93&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=93',
                department:'d_4',
                position: 'p_3'},
{id: 'u_95', 
                text: '胡某某', 
                name: '胡某某', 
                phone: '18208175220', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=95&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=95&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=95&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=95&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=95',
                department:'d_4',
                position: 'p_3'},
{id: 'u_96', 
                text: '王婷婷', 
                name: '王婷婷', 
                phone: '13550257470', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=96&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=96&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=96&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=96&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=96',
                department:'d_4',
                position: 'p_3'},
{id: 'u_10', 
                text: '刘学峰', 
                name: '刘学峰', 
                phone: '15283126855', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=10&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=10&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=10&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=10&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=10',
                department:'d_2',
                position: 'p_3'},
{id: 'u_13', 
                text: '冉杰', 
                name: '冉杰', 
                phone: '15295774336', 
                iconSkin: 'user', 
                type: 'user', 
                enable: 1, 
                imgUrl:'static.php?type=avatar&uid=13&size=small&engine=LOCAL',
                avatar_small:'static.php?type=avatar&uid=13&size=small&engine=LOCAL',
                avatar_middle:'static.php?type=avatar&uid=13&size=middle&engine=LOCAL',
                avatar_big:'static.php?type=avatar&uid=13&size=big&engine=LOCAL',
                spaceurl:'?r=user/home/index&uid=13',
                department:'d_2',
                position: 'p_3'},

			// ],
			// positioncategory:[
				{id: 'f_1', text: '默认分类', name: '默认分类', type: 'positioncategory', pId: 'f_0',open: 1,nocheck:true
},

			// ]
		];

		var _filter = function(data, matcher){
			var results = [];
			if(!matcher || typeof matcher !== "function") {
				return data;
			}
			for (var i = 0, len = data.length; i < len; i++) {
				if(matcher(data[i])){
					results.push(data[i]);
				}
			}
			return results;
		}

		Ewos.data = {
			filter: function(matcher) {
				return _filter(allData, matcher);
			},

			get: function() {
				var argu = arguments,
					matcher,
					ret = [];
				if(!argu.length || argu[0] == null) {
					return allData;
				}
				if(typeof argu[argu.length - 1] == "function") {
					matcher = argu[argu.length - 1];
					Array.prototype.pop.call(argu);
				}
				if(!argu.length && matcher) {
					return this.filter(matcher);
				} else {
					for(var i = 0; i < argu.length; i++) {
						var _ret = this.filter(function(data){
							return data && (data.type === argu[i] || data.iconSkin === argu[i]);
						})
						ret =  ret.concat(_ret);
					}
					return _filter(ret, matcher);
				}
			},

			getItem: function(/*id1, id2...*/) {
				var results = [],
					argu = arguments;

				for(var i = 0, len = argu.length; i < len; i++) {
					results = results.concat(this.filter(function(data){
						return data.id === argu[i];
					}))
				}

				return results;
			},
			getUser: function(id){
				var ret,
					deptInfo,
					posInfo;
				if(id) {
					if(id.charAt(0) !== "u") {
						id = "u_" + id;
					}
					ret = this.getItem(id)[0] || {};
					deptInfo = this.getItem(ret.department)[0];
					posInfo = this.getItem(ret.position)[0];
					ret = $.extend({}, ret, {
						department: deptInfo ? deptInfo.name : "",
						position: posInfo ? posInfo.name: ""
					});
				}
				return ret;
			},
			
			includes: function(ins){
				return this.getItem.apply(this, ins);
			}
		}
	} catch(e) {
		throw new Error("(Ewos.data): 模板解析错误" )
	}
})();